import random

ASSISTANT_NAMES = [
    "Floury Potter",
    "Dougharella",
    "Bready McBreadface",
    "Crustopher",
    "Dough-natello",
    "Cinnabun",
    "Flourence",
    "Glutenberg",
    "Yeastopher",
    "Bun Solo",
    "Loafy Skywalker",
    "Dough-bi-Wan",
    "Breadwin",
    "Kneady",
    "Breadnard",
    "Rye-an",
    "Dough-lores",
    "Proofie",
    "Artie San",
    "Crumbelina",
    "Bread Pitt",
    "Jane Dough",
    "Danny DeVito-st",
    "Pita Parker",
    "Leonardo DiCapri-oat",
    "Meryl Wheat",
    "Ryeling Stones",
    "Whole Wheatley",
    "Ciabatta Bing",
    "Sourdough Sam",
    "Vincent Van Dough",
    "Toast Malone",
    "Bun-edict Cumberbatch",
]

ADJECTIVES = [
    "Bubbly",
    "Crusty",
    "Tangy",
    "Proofed",
    "Fermented",
    "Wild",
    "Gassy",
    "Floury",
    "Chewy",
    "Crispy",
    "Rustic",
    "Over-Proofed",
    "Under-Proofed",
    "Toasty",
    "Artisanal",
    "Hydrated",
    "Golden",
    "Friendly",
    "Sweet",
    "Graceful",
    "Elegant",
    "Responsible",
    "Punctual",
    "Wholesome",
    "Upper-Crust",
    "Half-Baked",
    "Well-Kneaded",
    "Reliable",
    "Cheerful",
    "Grain-y",
    "Ever-so-supportive",
]


def generate_assistant_name() -> str:
    adjective = random.choice(ADJECTIVES)
    name = random.choice(ASSISTANT_NAMES)
    return f"The {adjective} {name}"
